#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

# Export LOG_FILE (See etc/log4j2.properties)
if [[ ${OS_NAME} == CYGWIN* ]]; then
   export LOG_FILE=$LOG_DIR\\$EXECUTABLE.log
   CLASSPATH="$(cygpath -wp "$CLASSPATH")"
else
   export LOG_FILE=$LOG_DIR/$EXECUTABLE.log
fi

JAVA_ARGS="-DgemfirePropertyFile=$GEMFIRE_PROPERTY_FILE \
    -Dgemfire.cache-xml-file=$GEODE_CLIENT_CONFIG_FILE"
export JAVA_ARGS="$JAVA_ARGS -Dgfsh.log-level=info -Dgfsh.log-dir=$LOG_DIR"

gfsh
